repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/jtdowney/pre-commit-gleam
    rev: v1.0.0
    hooks:
      - id: format
      - id: check
  - repo: local
    hooks:
      - id: prettier
        name: prettier --check
        entry: bunx prettier --check
        language: system
        files: ^src/.*\.{md|json|mjs}$
      - id: eslint
        name: eslint
        entry: bun run lint
        language: system
        files: ^src/.*\.mjs$
        pass_filenames: false
