//// Generated by protoc-gen-gleam. DO NOT EDIT.
////
//// Source: migration.proto
////
//// Proto package:

import gleam/list
import gleam_protobuf/wire

pub type Algorithm {
  AlgorithmUnspecified
  AlgorithmSha1
  AlgorithmSha256
  AlgorithmSha512
  AlgorithmMd5
}

pub fn algorithm_to_int(v: Algorithm) -> Int {
  case v {
    AlgorithmUnspecified -> 0
    AlgorithmSha1 -> 1
    AlgorithmSha256 -> 2
    AlgorithmSha512 -> 3
    AlgorithmMd5 -> 4
  }
}

pub fn algorithm_from_int(i: Int) -> Result(Algorithm, wire.DecodeError) {
  case i {
    0 -> Ok(AlgorithmUnspecified)
    1 -> Ok(AlgorithmSha1)
    2 -> Ok(AlgorithmSha256)
    3 -> Ok(AlgorithmSha512)
    4 -> Ok(AlgorithmMd5)
    v -> Error(wire.UnknownEnumValue("Algorithm", v))
  }
}

pub fn algorithm_to_string(v: Algorithm) -> String {
  case v {
    AlgorithmUnspecified -> "unspecified"
    AlgorithmSha1 -> "sha1"
    AlgorithmSha256 -> "sha256"
    AlgorithmSha512 -> "sha512"
    AlgorithmMd5 -> "md5"
  }
}

pub type DigitCount {
  DigitCountUnspecified
  DigitCountSix
  DigitCountEight
}

pub fn digit_count_to_int(v: DigitCount) -> Int {
  case v {
    DigitCountUnspecified -> 0
    DigitCountSix -> 1
    DigitCountEight -> 2
  }
}

pub fn digit_count_from_int(i: Int) -> Result(DigitCount, wire.DecodeError) {
  case i {
    0 -> Ok(DigitCountUnspecified)
    1 -> Ok(DigitCountSix)
    2 -> Ok(DigitCountEight)
    v -> Error(wire.UnknownEnumValue("DigitCount", v))
  }
}

pub fn digit_count_to_string(v: DigitCount) -> String {
  case v {
    DigitCountUnspecified -> "unspecified"
    DigitCountSix -> "six"
    DigitCountEight -> "eight"
  }
}

pub type OtpType {
  OtpTypeUnspecified
  OtpTypeHotp
  OtpTypeTotp
}

pub fn otp_type_to_int(v: OtpType) -> Int {
  case v {
    OtpTypeUnspecified -> 0
    OtpTypeHotp -> 1
    OtpTypeTotp -> 2
  }
}

pub fn otp_type_from_int(i: Int) -> Result(OtpType, wire.DecodeError) {
  case i {
    0 -> Ok(OtpTypeUnspecified)
    1 -> Ok(OtpTypeHotp)
    2 -> Ok(OtpTypeTotp)
    v -> Error(wire.UnknownEnumValue("OtpType", v))
  }
}

pub fn otp_type_to_string(v: OtpType) -> String {
  case v {
    OtpTypeUnspecified -> "unspecified"
    OtpTypeHotp -> "hotp"
    OtpTypeTotp -> "totp"
  }
}

pub type MigrationPayloadOtpParameters {
  MigrationPayloadOtpParameters(
    secret: BitArray,
    name: String,
    issuer: String,
    algorithm: Algorithm,
    digits: DigitCount,
    otp_type: OtpType,
    counter: Int,
  )
}

const field_migration_payload_otp_parameters_secret: Int = 1

const field_migration_payload_otp_parameters_name: Int = 2

const field_migration_payload_otp_parameters_issuer: Int = 3

const field_migration_payload_otp_parameters_algorithm: Int = 4

const field_migration_payload_otp_parameters_digits: Int = 5

const field_migration_payload_otp_parameters_otp_type: Int = 6

const field_migration_payload_otp_parameters_counter: Int = 7

pub fn encode_migration_payload_otp_parameters(
  msg: MigrationPayloadOtpParameters,
) -> BitArray {
  let MigrationPayloadOtpParameters(
    secret,
    name,
    issuer,
    algorithm,
    digits,
    otp_type,
    counter,
  ) = msg
  <<
    wire.encode_bytes_field(
      field_migration_payload_otp_parameters_secret,
      secret,
    ):bits,
    wire.encode_string_field(field_migration_payload_otp_parameters_name, name):bits,
    wire.encode_string_field(
      field_migration_payload_otp_parameters_issuer,
      issuer,
    ):bits,
    wire.encode_int_field(
      field_migration_payload_otp_parameters_algorithm,
      algorithm_to_int(algorithm),
    ):bits,
    wire.encode_int_field(
      field_migration_payload_otp_parameters_digits,
      digit_count_to_int(digits),
    ):bits,
    wire.encode_int_field(
      field_migration_payload_otp_parameters_otp_type,
      otp_type_to_int(otp_type),
    ):bits,
    wire.encode_int_field(
      field_migration_payload_otp_parameters_counter,
      counter,
    ):bits,
  >>
}

type MigrationPayloadOtpParametersAcc {
  MigrationPayloadOtpParametersAcc(
    secret: BitArray,
    name: String,
    issuer: String,
    algorithm: Algorithm,
    digits: DigitCount,
    otp_type: OtpType,
    counter: Int,
  )
}

pub fn decode_migration_payload_otp_parameters(
  buf: BitArray,
) -> Result(MigrationPayloadOtpParameters, wire.DecodeError) {
  let init =
    MigrationPayloadOtpParametersAcc(
      secret: <<>>,
      name: "",
      issuer: "",
      algorithm: AlgorithmUnspecified,
      digits: DigitCountUnspecified,
      otp_type: OtpTypeUnspecified,
      counter: 0,
    )
  case
    decode_fields(buf, init, migration_payload_otp_parameters_field_handler)
  {
    Error(e) -> Error(e)
    Ok(acc) ->
      Ok(MigrationPayloadOtpParameters(
        secret: acc.secret,
        name: acc.name,
        issuer: acc.issuer,
        algorithm: acc.algorithm,
        digits: acc.digits,
        otp_type: acc.otp_type,
        counter: acc.counter,
      ))
  }
}

fn migration_payload_otp_parameters_field_handler(
  field_number: Int,
  wire_type: Int,
  rest: BitArray,
  acc: MigrationPayloadOtpParametersAcc,
) -> Result(#(MigrationPayloadOtpParametersAcc, BitArray), wire.DecodeError) {
  case field_number {
    n if n == field_migration_payload_otp_parameters_secret ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          Ok(#(MigrationPayloadOtpParametersAcc(..acc, secret: bytes), r))
      }
    n if n == field_migration_payload_otp_parameters_name ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(MigrationPayloadOtpParametersAcc(..acc, name: s), r))
          }
      }
    n if n == field_migration_payload_otp_parameters_issuer ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) ->
              Ok(#(MigrationPayloadOtpParametersAcc(..acc, issuer: s), r))
          }
      }
    n if n == field_migration_payload_otp_parameters_algorithm ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) ->
          case algorithm_from_int(v) {
            Error(e) -> Error(e)
            Ok(ev) ->
              Ok(#(MigrationPayloadOtpParametersAcc(..acc, algorithm: ev), r))
          }
      }
    n if n == field_migration_payload_otp_parameters_digits ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) ->
          case digit_count_from_int(v) {
            Error(e) -> Error(e)
            Ok(ev) ->
              Ok(#(MigrationPayloadOtpParametersAcc(..acc, digits: ev), r))
          }
      }
    n if n == field_migration_payload_otp_parameters_otp_type ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) ->
          case otp_type_from_int(v) {
            Error(e) -> Error(e)
            Ok(ev) ->
              Ok(#(MigrationPayloadOtpParametersAcc(..acc, otp_type: ev), r))
          }
      }
    n if n == field_migration_payload_otp_parameters_counter ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) ->
          Ok(#(MigrationPayloadOtpParametersAcc(..acc, counter: v), r))
      }
    _ ->
      case wire.skip_field(rest, wire_type) {
        Ok(r) -> Ok(#(acc, r))
        Error(e) -> Error(e)
      }
  }
}

pub type MigrationPayload {
  MigrationPayload(
    otp_parameters: List(MigrationPayloadOtpParameters),
    version: Int,
    batch_size: Int,
    batch_index: Int,
    batch_id: Int,
  )
}

const field_migration_payload_otp_parameters: Int = 1

const field_migration_payload_version: Int = 2

const field_migration_payload_batch_size: Int = 3

const field_migration_payload_batch_index: Int = 4

const field_migration_payload_batch_id: Int = 5

pub fn encode_migration_payload(msg: MigrationPayload) -> BitArray {
  let MigrationPayload(
    otp_parameters,
    version,
    batch_size,
    batch_index,
    batch_id,
  ) = msg
  <<
    wire.encode_repeated_messages(
      field_migration_payload_otp_parameters,
      otp_parameters,
      encode_migration_payload_otp_parameters,
    ):bits,
    wire.encode_int_field(field_migration_payload_version, version):bits,
    wire.encode_int_field(field_migration_payload_batch_size, batch_size):bits,
    wire.encode_int_field(field_migration_payload_batch_index, batch_index):bits,
    wire.encode_int_field(field_migration_payload_batch_id, batch_id):bits,
  >>
}

type MigrationPayloadAcc {
  MigrationPayloadAcc(
    otp_parameters: List(MigrationPayloadOtpParameters),
    version: Int,
    batch_size: Int,
    batch_index: Int,
    batch_id: Int,
  )
}

pub fn decode_migration_payload(
  buf: BitArray,
) -> Result(MigrationPayload, wire.DecodeError) {
  let init =
    MigrationPayloadAcc(
      otp_parameters: [],
      version: 0,
      batch_size: 0,
      batch_index: 0,
      batch_id: 0,
    )
  case decode_fields(buf, init, migration_payload_field_handler) {
    Error(e) -> Error(e)
    Ok(acc) ->
      Ok(MigrationPayload(
        otp_parameters: list.reverse(acc.otp_parameters),
        version: acc.version,
        batch_size: acc.batch_size,
        batch_index: acc.batch_index,
        batch_id: acc.batch_id,
      ))
  }
}

fn migration_payload_field_handler(
  field_number: Int,
  wire_type: Int,
  rest: BitArray,
  acc: MigrationPayloadAcc,
) -> Result(#(MigrationPayloadAcc, BitArray), wire.DecodeError) {
  case field_number {
    n if n == field_migration_payload_otp_parameters ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(body, r)) ->
          case decode_migration_payload_otp_parameters(body) {
            Error(e) -> Error(e)
            Ok(m) ->
              Ok(#(
                MigrationPayloadAcc(..acc, otp_parameters: [
                  m,
                  ..acc.otp_parameters
                ]),
                r,
              ))
          }
      }
    n if n == field_migration_payload_version ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) -> Ok(#(MigrationPayloadAcc(..acc, version: v), r))
      }
    n if n == field_migration_payload_batch_size ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) -> Ok(#(MigrationPayloadAcc(..acc, batch_size: v), r))
      }
    n if n == field_migration_payload_batch_index ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) -> Ok(#(MigrationPayloadAcc(..acc, batch_index: v), r))
      }
    n if n == field_migration_payload_batch_id ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) -> Ok(#(MigrationPayloadAcc(..acc, batch_id: v), r))
      }
    _ ->
      case wire.skip_field(rest, wire_type) {
        Ok(r) -> Ok(#(acc, r))
        Error(e) -> Error(e)
      }
  }
}

// --- Shared decode helpers -------------------------------------------

fn decode_fields(
  buf: BitArray,
  acc: a,
  handler: fn(Int, Int, BitArray, a) -> Result(#(a, BitArray), wire.DecodeError),
) -> Result(a, wire.DecodeError) {
  case buf {
    <<>> -> Ok(acc)
    _ ->
      case wire.decode_tag(buf) {
        Error(e) -> Error(e)
        Ok(#(field_number, wire_type, rest)) ->
          case handler(field_number, wire_type, rest, acc) {
            Error(e) -> Error(e)
            Ok(#(new_acc, new_rest)) ->
              decode_fields(new_rest, new_acc, handler)
          }
      }
  }
}
